# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFilterupcominggames():
  def setup_method(self, method):
    chrome_option = webdriver.ChromeOptions()
    chrome_option.add_argument("--headless")
    firefox_options = webdriver.FirefoxOptions()
    firefox_options.add_argument("--headless")
    edge_options = webdriver.EdgeOptions()
    edge_options.add_argument("--headless")
    drivers = [webdriver.Chrome(options=chrome_option), webdriver.Firefox(options=firefox_options),
               webdriver.Edge(options=edge_options)]
    self.driver = drivers[0]
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_filterupcominggames(self):
    # Test name: Filter upcoming games
    # Step # | name | target | value
    # 1 | open | https://usahockeytv.com |
    prod = "https://usahockeytv.com"
    dev =   "https://stage.usah.visaic.tv/"
    self.driver.get(dev)
    # 2 | setWindowSize | 1497x866 | 
    self.driver.set_window_size(1497, 866)

    self.driver.implicitly_wait(30)
    # 3 | click | css=.dropdown-menu-hover-wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-menu-hover-wrapper").click()
    # 4 | click | css=.dropdown-item:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(1)").click()
    # 5 | click |
    self.driver.find_element(By.CSS_SELECTOR, ".vc-appearance-none").click()

    # 7 | click | css=.select-wrapper:nth-child(1) > .custom-select |
    element = self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(1) > .custom-select")
    self.driver.execute_script("arguments[0].click();", element)
    self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(1) > .custom-select").click()
    # 8 | select | css=.select-wrapper:nth-child(1) > .custom-select | label=NTDP
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(1) > .custom-select")
    dropdown.find_element(By.XPATH, "//*[@id=\"app\"]/div[2]/div/div[2]/label[1]/select/option[2]").click()

    # 9 | click | css=.select-wrapper:nth-child(2) > .custom-select |
    self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(2) > .custom-select").click()
    # 10 | select | css=.select-wrapper:nth-child(2) > .custom-select | label=NTDP U17
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(2) > .custom-select")
    dropdown.find_element(By.XPATH, "//*[@id=\"app\"]/div[2]/div/div[2]/label[2]/select/option[2]").click()
    # 11 | click | css=.select-wrapper:nth-child(3) > .custom-select |
    self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(3) > .custom-select").click()
    # 12 | click | css=.select-wrapper:nth-child(1) > .custom-select |
    self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(1) > .custom-select").click()
    # 13 | select | css=.select-wrapper:nth-child(1) > .custom-select | label=National Championship
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(1) > .custom-select")
    dropdown.find_element(By.XPATH, "//*[@id=\"app\"]/div[2]/div/div[2]/label[1]/select/option[3]").click()
    # 14| click | css=.select-wrapper:nth-child(2) > .custom-select |
    self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(2) > .custom-select").click()
    # 15 | select | css=.select-wrapper:nth-child(2) > .custom-select | label=Youth Tier I
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(2) > .custom-select")
    dropdown.find_element(By.XPATH, "//*[@id=\"app\"]/div[2]/div/div[2]/label[2]/select/option[2]").click()
    # 16 | click | css=.select-wrapper:nth-child(3) > .custom-select |
    self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(3) > .custom-select").click()
    # 17 | select | css=.select-wrapper:nth-child(3) > .custom-select | label=Youth Tier I
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".select-wrapper:nth-child(3) > .custom-select")
    dropdown.find_element(By.XPATH, "//*[@id=\"app\"]/div[2]/div/div[2]/label[3]/select/option[2]").click()