# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreategame():
  def setup_method(self, method):
    # self.driver = webdriver.Chrome()
    chrome_option = webdriver.ChromeOptions()
    chrome_option.add_argument("--headless")
    firefox_options = webdriver.FirefoxOptions()
    firefox_options.add_argument("--headless")
    edge_options = webdriver.EdgeOptions()
    edge_options.add_argument("--headless")
    drivers = [webdriver.Chrome(options=chrome_option), webdriver.Firefox(options=firefox_options),
               webdriver.Edge(options=edge_options)]
    self.driver = drivers[0]
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creategame(self):
    # Test name: Create game
    # Step # | name | target | value
    # 1 | open | https://rudy.visaic.com.ua/events | 
    self.driver.get("https://rudy.visaic.com.ua/events")
    # 2 | setWindowSize | 2064x1120 | 
    self.driver.set_window_size(2064, 1120)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | usah.admin@visaic.com
    self.driver.find_element(By.ID, "email").send_keys("usah.admin@visaic.com")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | usah1234
    self.driver.find_element(By.ID, "password").send_keys("usah1234")
    # 7 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 8 | click | linkText=Add New Game | 
    self.driver.find_element(By.LINK_TEXT, "Add New Game").click()
    # 9 | click | name=event_category_id | 
    self.driver.find_element(By.NAME, "event_category_id").click()
    # 10 | select | name=event_category_id | label=NTDP
    dropdown = self.driver.find_element(By.NAME, "event_category_id")
    dropdown.find_element(By.XPATH, "//*[@id=\"tab-main-content\"]/div[1]/div[1]/div[1]/select/option[2]").click()
    # 11 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 12 | type | id=name | TEAM 1 VS TEAM 2
    self.driver.find_element(By.ID, "name").send_keys("TEAM 1 VS TEAM 2")
    # 13 | click | id=caption | 
    self.driver.find_element(By.ID, "caption").click()
    # 14 | type | id=caption | TEST
    self.driver.find_element(By.ID, "caption").send_keys("TEST")
    # 15 | click | id=venue | 
    self.driver.find_element(By.ID, "venue").click()
    # 16 | type | id=venue | ARENA 15
    self.driver.find_element(By.ID, "venue").send_keys("ARENA 15")
    # 17 | click | css=.btn-success:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success:nth-child(1)").click()
    # 18 | click | css=.w-100:nth-child(6) .btn-info > .fa | 
    self.driver.find_element(By.CSS_SELECTOR, ".w-100:nth-child(6) .btn-info > .fa").click()
    # 19 | click | linkText=Delete game | 
    self.driver.find_element(By.LINK_TEXT, "Delete game").click()
    # 20 | click | css=.confirm-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".confirm-btn")
    self.driver.execute_script("arguments[0].click();", element)
    # 21 | click | css=.fa-angle-down |
    self.driver.find_element(By.CSS_SELECTOR, ".fa-angle-down").click()
    # 22 | click | linkText=Logout |
    element2 = self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(3)")
    self.driver.execute_script("arguments[0].click();", element2)
  
