# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpcominggames():
  def setup_method(self, method):
    # headless Chrome Driver
    chrome_option = webdriver.ChromeOptions()
    chrome_option.add_argument("--headless")
    firefox_options = webdriver.FirefoxOptions()
    firefox_options.add_argument("--headless")
    edge_options = webdriver.EdgeOptions()
    edge_options.add_argument("--headless")
    drivers = [webdriver.Chrome(options=chrome_option), webdriver.Firefox(options=firefox_options),
               webdriver.Edge(options=edge_options)]
    self.driver = drivers[0]
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_upcominggames(self):
    # Test name: upcoming games
    # Step # | name | target | value
    # 1 | open | https://usahockeytv.com/ |
    prod = "https://usahockeytv.com"
    dev = "https://stage.usah.visaic.tv/"
    self.driver.get(dev)
    # 2 | setWindowSize | 1505x577 | 
    self.driver.set_window_size(1505, 577)
    # 3
    self.driver.implicitly_wait(30)

    # 4 | click | css=.dropdown-menu-hover-wrapper |
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-menu-hover-wrapper").click()

    # 5 | click | css=.dropdown-item:nth-child(1) |
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(1)").click()
    # 6 | assertElementPresent | css=.content-wrapper |
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".content-wrapper")
    assert len(elements) > 0
  
