# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatesubscription():
  def setup_method(self, method):
    # self.driver = webdriver.Chrome()
    chrome_option = webdriver.ChromeOptions()
    chrome_option.add_argument("--headless")
    firefox_options = webdriver.FirefoxOptions()
    firefox_options.add_argument("--headless")
    edge_options = webdriver.EdgeOptions()
    edge_options.add_argument("--headless")
    drivers = [webdriver.Chrome(options=chrome_option), webdriver.Firefox(options=firefox_options),
               webdriver.Edge(options=edge_options)]
    self.driver = drivers[0]
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createsubscription(self):
    # Test name: Create subscription
    # Step # | name | target | value
    # 1 | open | https://rudy.visaic.com.ua/subscriptions/create | 
    self.driver.get("https://rudy.visaic.com.ua/subscriptions/create")
    # 2 | setWindowSize | 1200x1120 | 
    self.driver.set_window_size(1200, 1120)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | usah.admin@visaic.com
    self.driver.find_element(By.ID, "email").send_keys("usah.admin@visaic.com")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | usah1234
    self.driver.find_element(By.ID, "password").send_keys("usah1234")
    # 7 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 8 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 9 | type | id=name | test sub
    self.driver.find_element(By.ID, "name").send_keys("test sub")
    # 10 | click | name=event_category_id | 
    self.driver.find_element(By.NAME, "event_category_id").click()
    # 11 | select | name=event_category_id | label=NTDP
    dropdown = self.driver.find_element(By.NAME, "event_category_id")
    dropdown.find_element(By.XPATH, "/html/body/div/div[2]/div[2]/div/div[2]/div/div/div/form/div[1]/div/div[1]/div[3]/div/div[2]/select/option[2]").click()
    # 12 | click | id=description | 
    self.driver.find_element(By.ID, "description").click()
    # 13 | type | id=description | test sub runs
    self.driver.find_element(By.ID, "description").send_keys("test sub runs")
    # 14 | click | css=.btn-success | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    # 15 | click | css=tr:nth-child(1) .btn > .fa | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .btn > .fa").click()
    # 16 | click | linkText=Delete Subscription | 
    self.driver.find_element(By.LINK_TEXT, "Delete Subscription").click()
    # 17 | click | css=.confirm-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".confirm-btn")
    self.driver.execute_script("arguments[0].click();", element)
    # 18 | click | css=.fa-angle-down |
    self.driver.find_element(By.CSS_SELECTOR, ".fa-angle-down").click()
    # 19 | click | linkText=Logout |
    element2 = self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(3)")
    self.driver.execute_script("arguments[0].click();", element2)
  
